# Application name
spring.application.name=Atsumeru

# Server default port
server.port=31337

# Active (default) profile
spring.profiles.active=production

# GSON
spring.mvc.converters.preferred-json-mapper=gson

# Increase header buffer size
server.max-http-request-header-size=15360